### ISSUE TITLE
Commited Secrets 

### ISSUE THREAD

**Issue by stephenandary** [cbr9/dotfiles#1]
Just want to check and make sure your commited ssh keys were not sensitive.

**Comment by cbr9** [comment]
Hey thanks for your comment. You mean my public keys?

**Comment by stephenandary** [comment]
I was not sure, glad that is what those are! I came to this repo from a 1password post to get ssh agent working with vscode, and am new to nix. 

Closing issue now!

**Comment by cbr9** [comment]
Yeah, they're not private keys, no worries :)
